routes/web.php
<?php

use App\Http\Controllers\admin\{AnswersController,
    AuthController,
    ClassesController,
    GeneralController,
    QuestionController,
    ResultController,
    SectionsController,
    StudentController,
    TestController,
    UserController};
use App\Http\Controllers\front\FrontController;
use App\Http\Controllers\WordParserController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

// Auth admin
Route::get('/login-admin', function () { return view('admin.login');})->name('admin.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::post('/authenticate-admin', [AuthController::class, 'authenticate_admin'])->name('admin.authenticate');

// Auth student
Route::get('/login-student', function () { return view('admin.students.login');})->name('student.login');
Route::post('/authenticate-student', [\App\Http\Controllers\student\AuthController::class, 'authenticate_student'])->name('student.authenticate');


//Dashboard
Route::group([
    'prefix' => '/dashboard',
    'middleware' => ['admin'],
    'as' => 'dashboard.'
],
    function () {
    Route::get('/', [GeneralController::class, 'dashboard_index'])->name('index');
    //datatable
    Route::get('users/all', [UserController::class, 'all_users'])->name('users.all');
    Route::get('classes/all', [ClassesController::class, 'all_classes'])->name('classes.all');
    Route::get('sections/{id}/get_all', [SectionsController::class, 'all_sections'])->name('sections.all');
    Route::get('questions/all', [QuestionController::class, 'all_questions'])->name('questions.all');
    Route::get('students/all', [StudentController::class, 'all_students'])->name('students.all');
    Route::get('questions/{question}/answers', [AnswersController::class, 'addAnswers'])->name('questions.answers');

    Route::get('tests/all', [TestController::class, 'all_tests'])->name('tests.all');
    Route::get('questions/{id}/get_all', [QuestionController::class, 'all_questions_test'])->name('questions.test');
    Route::delete('tests/{test_id}/remove_question/{question_id}', [TestController::class, 'remove_question'])->name('tests.remove_question');
    Route::post('tests/{test_id}/add_random_questions', [QuestionController::class, 'add_random_questions'])->name('tests.add_random_questions');
    Route::post('tests/{id}/add_question', [TestController::class, 'add_question'])->name('tests.add_question');
    Route::get('student/submitted-exam-results', [ResultController::class, 'submittedExamResults'])->name('submitted_exam_results');
    Route::get('admin/view-class-results', [ResultController::class, 'viewClassResults'])->name('view_class_results');
    Route::get('results/class/all/{class_id}', [ResultController::class, 'getViewClassResults'])->name('view_class_results.all');
    Route::get('admin/view/previous-tests/{result}', [ResultController::class, 'previousTests'])->name('previous.tests.view');
    Route::post('/questions/upload', [WordParserController::class, 'upload'])->name('questions.upload');


        //resource
    Route::resources([
        'users' => UserController::class,
    ]);
    Route::resources([
        'classes' => ClassesController::class,
    ]);
    Route::resources([
        'sections' => SectionsController::class,
    ]);
    Route::resources([
        'questions' => QuestionController::class,
    ]);
    Route::resources([
        'students' =>StudentController::class,
    ]);
    Route::resources([
        'tests' => TestController::class,
    ]);
    Route::resources([
        'answers' =>AnswersController::class,
    ]);
});



Route::group([
    'prefix' => '/student',
    'middleware' => ['student'],
    'as' => 'student.'
           ],function (){

    Route::post('test/show/',  [FrontController::class, 'showTest'])->name('show.test')->middleware('checkTestCompletion');
    Route::get('available-tests', [FrontController::class, 'availableTests'])->name('available.tests');

    Route::post('tests/submit/{test_id}', [FrontController::class, 'submitTest'])->name('submit.test')->middleware('checkTestCompletion');
    Route::get('/results', [FrontController::class, 'showResults'])->name('test.result');

});

Route::get('student/all-results/{student_id}', [ResultController::class, 'allResults'])->name('student.all-results-students');

Route::get('student/all-results', [ResultController::class, 'index'])->name('student.all-results');

// View Test Results
Route::get('/student/test/result/view/{result}', [ResultController::class, 'viewTestResults'])->name('student.test.result.view');
Route::get('/student/show/testResult/view/{result}', [ResultController::class, 'viewTestResultsForAdmin'])->name('student.show.test.result.admin');

// Delete Test Results
Route::delete('/student/test/result/delete/{id}', [ResultController::class, 'deleteTestResults'])->name('student.test.result.delete');
//

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use App\Models\TemporaryFile;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    // Must delete this after user it
    public function register_first_admin(Request $request)
    {
        $user = User::create([
            'name' => 'AraCoders',
            'email' => 'admin@aracoders.com',
            'password' => Hash::make('aracoders'),
            'role' => 1,
        ]);

        return response()->json(['success' => "true", 'user' => $user]);
    }

    public function index()
    {
        $users = User::all();
        return view('admin.users.index', ['users' => $users]);
    }

    public function all_users()
    {
        $users = User::latest()->get();
        return $users;
    }


    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'max:255'],
            'email' => ['required', 'email', 'unique:users'],
            'password' => ['required'],
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role' => $request->role,
        ]);


        return response()->json(['success' => "true", 'user' => $user], 201);
    }

    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.users.edit', ['user' => $user]);
    }


    public function update(Request $request, User $user)
    {
        $request->validate([
            'email' => ['email', 'unique:users,email,' . $user->id],
        ]);

        if($request->name)
        {
            $user->name = $request->name;
            $user->save();
        }

        if ($request->email) {
            $user->email = $request->email;
            $user->save();
        }

        if ($request->password) {
            $user->password = Hash::make($request->password);
            $user->save();
        }

        return $user;
    }

    public function show($id)
    {
        //
    }

    public function destroy($id)
    {
        $list_ids = explode(",", $id);
        User::whereIn('id', $list_ids)->delete();
        return $list_ids;
    }




}

resources/views/admin/users/create.blade.php
@extends('admin.master')
@section('navbar-title', 'إضافة مدير')

@section('content')
<div class="row">
    <div class=" col-12">
        <div class="card">
            <div class="card-header pb-0 px-3 ">
                <h6 class="mb-0 text-lg">إضافة مدير جديد</h6>
            </div>
            
            <div class="card-body pt-4 p-3">

                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm"></span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <script>
                    $("#alert_message").on("close.bs.alert", function () {
                        // hide the alert >>> not remove it
                        $("#alert_message").hide();
                        return false;
                    });
                </script>

                <form role="form" id="add_user_form" class="text-end">
                    <div class="input-group input-group-outline my-3">
                        <label class="form-label">الاسم</label>
                        <input id="name" type="text" class="form-control">
                    </div>
                    <div class="input-group input-group-outline my-3">
                      <label class="form-label">الإيميل</label>
                      <input id="email" type="email" class="form-control">
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">كلمة المرور</label>
                      <input id="password" type="password" class="form-control">
                    </div>
                    
                    
                    

                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-primary w-50 my-4 mb-2 text-lg">
                        <span id="button_submit_text">إضافة</span>
                        <div class="spinner" style="display: none;">
                          <div class="double-bounce1"></div>
                          <div class="double-bounce2"></div>
                        </div>
                      </button>
                    </div>
                  </form>
            </div>
        </div>
    </div>
</div>






<script>
    $('#add_user_form').on('submit', function(e) {
       e.preventDefault();
 

       $("#button_submit_text").hide();
       $(".spinner").show();
       $("#alert_message").hide();

       var uploadData = new FormData();

       var name = $('#name').val();
       var email = $('#email').val();
       var password = $('#password').val();

       
       
       uploadData.append('name',name);
       uploadData.append('email',email);
       uploadData.append('password',password);
       uploadData.append('role',1);

       
       $.ajax({
           type: "POST",
           headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
           url: '{{route('dashboard.users.store')}}',
           data: uploadData,
           contentType: false,
           processData: false,
           statusCode: {
                422: function(error) {
                    // Only if your server returns a 422 status code can it come in this block. :-)
                    var errors = error.responseJSON.errors;
                    // console.log(errors);
                    var alert_message = document.getElementById("alert_message");
                    $("#alert_message").show();
                    var ul = document.getElementById("errors_list");
                    $('#errors_list').empty();
                    Object.entries(errors).forEach(function([key, value]){
                        var li = document.createElement("li");
                        li.appendChild(document.createTextNode(value));
                        ul.appendChild(li);
                    }
                    );
                },
                403: function() {
                    // Only if your server returns a 403 status code can it come in this block. :-)
                }
            },
           success:function(data){
                console.log("success");
                console.log(data);
                $("#button_submit_text").show();
                $(".spinner").hide();
                window.location = '{{route('dashboard.users.index')}}';
           },
           error:function(error){
                console.log("error");
                console.log(error);
                $("#button_submit_text").show();
                $(".spinner").hide();
                // myToast.show();
           }
       });
   });
</script>



@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.master')
@section('navbar-title', 'تعديل المدير')

@section('content')
<div class="row">
    <div class=" col-12">
        <div class="card">
            <div class="card-header pb-0 px-3 ">
                <h6 class="mb-0 text-lg">تعديل المدير </h6>
            </div>
            
            <div class="card-body pt-4 p-3">
                <div class="row gx-4 mb-2">
                    
                    <div class="col-auto my-auto">
                      <div class="h-100">
                        <h5 class="mb-1">
                            {{$user->name}}
                        </h5>
                        
                              مدير
                          
                      </div>
                    </div>
                  </div>


                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm">حصل خطأ اثناء تعديل بيانات المدير</span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div style="display: none"  class="alert alert-success alert-dismissible text-white" role="alert" id="succcess_message">
                    <span class="text-sm">تم تعديل بيانات المدير</span>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <script>
                    $("#alert_message,#succcess_message").on("close.bs.alert", function () {
                        // hide the alert >>> not remove it
                        $("#alert_message").hide();
                        $("#succcess_message").hide();
                        return false;
                    });
                </script>

                <form role="form" id="edit_user_form" class="text-end">
                    <div class="input-group input-group-outline my-3 is-filled">
                        <label class="form-label">الاسم</label>
                        <input id="name" type="text" class="form-control" value="{{$user->name}}">
                    </div>
                    <div class="input-group input-group-outline my-3 is-filled">
                      <label class="form-label">الإيميل</label>
                      <input id="email" type="email" class="form-control" value="{{$user->email}}">
                    </div>
                    <div class="input-group input-group-outline mb-3">
                      <label class="form-label">كلمة المرور</label>
                      <input id="password" type="password" class="form-control">
                    </div>
                    
                    

                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-primary w-50 my-4 mb-2 text-lg">
                        <span id="button_submit_text">تعديل</span>
                        <div class="spinner" style="display: none;">
                          <div class="double-bounce1"></div>
                          <div class="double-bounce2"></div>
                        </div>
                      </button>
                    </div>
                  </form>
            </div>
        </div>
    </div>
</div>


  






<script>
    $('#edit_user_form').on('submit', function(e) {
       e.preventDefault();
 

       $("#button_submit_text").hide();
       $(".spinner").show();
       $("#alert_message").hide();
       $("#succcess_message").hide();

       var uploadData = new FormData();

       var name = $('#name').val();
       var email = $('#email').val();
       var password = $('#password').val();
       var role = $('#select-role').val();
       var profile_image = $("input[name='profile_image']").val();
       
       
       uploadData.append('name',name);
       uploadData.append('email',email);
       uploadData.append('password',password);
       uploadData.append('_method','PUT');

       
       $.ajax({
           type: "POST",
           headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
           url: '{{route('dashboard.users.update',$user)}}',
           data: uploadData,
           contentType: false,
           processData: false,
           statusCode: {
                422: function(error) {
                    // Only if your server returns a 422 status code can it come in this block. :-)
                    var errors = error.responseJSON.errors;
                    // console.log(errors);
                    var alert_message = document.getElementById("alert_message");
                    $("#alert_message").show();
                    var ul = document.getElementById("errors_list");
                    $('#errors_list').empty();
                    Object.entries(errors).forEach(function([key, value]){
                        var li = document.createElement("li");
                        li.appendChild(document.createTextNode(value));
                        ul.appendChild(li);
                    }
                    );
                },
                403: function() {
                    // Only if your server returns a 403 status code can it come in this block. :-)
                }
            },
           success:function(data){
                console.log("success");
                console.log(data);
                $("#button_submit_text").show();
                $(".spinner").hide();
                $("#succcess_message").show();
                window.location = window.location;
           },
           error:function(error){
                console.log("error");
                console.log(error);
                $("#button_submit_text").show();
                $(".spinner").hide();
                $("#alert_message").show();
                // myToast.show();
           }
       });
   });
</script>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.master')
@section('page-title', 'المدراء')
@section('navbar-title', 'المدراء')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize pe-3">جدول المدراء</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
            <div class="button_datatable px-2">
                <a href="{{route('dashboard.users.create')}}" class="btn btn-success text-sm" id="add_new_user_button" type="button">
                    <i class="fa fa-plus"></i>
                    إضافة مدير جديد
                </a>
                <button class="btn btn-primary text-sm" id="selected_all_rows_button" type="button" >
                    <i class="fa fa-check-square-o"></i>
                    تحديد الكل
                </button>
                <button class="btn btn-secondary text-sm" id="deselected_all_rows_button" type="button" >
                    <i class="fa fa-times-circle"></i>
                    الغاء التحديد
                </button>
                <button class="btn btn-danger text-sm" id="selected_rows_delete_button" type="button">
                    <i class="fa fa-trash"></i>
                    حذف العناصر المحددة
                </button>
            </div>
            <div class="table-responsive p-0">
                <table class="table align-items-center mb-0 table-hover " id="users_table" style="width:100%">
                <thead>
                    <tr>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الاسم</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7 ps-2">الايميل</th>
                    <th class="text-center text-uppercase text-secondary text-s font-weight-bolder opacity-7">الدور</th>
                    <th class="text-secondary text-s opacity-7">الاجراءات</th>
                    </tr>
                </thead>
                </table>
            </div>
        </div>
      </div>
    </div>
  </div>

  <!--     toast start     -->
  <div class="position-fixed top-0 start-0 p-lg-3" style="z-index: 11">
    <div class="toast fade hide p-2 mt-2 bg-gradient-info" role="alert" aria-live="assertive" id="infoToast" aria-atomic="true">
        <div class="toast-header bg-transparent border-0">
          <i class="material-icons text-white ms-2">notifications</i>
          <span class="ms-auto text-white font-weight-bold text-lg">اشعار</span>
          <i class="fas fa-times text-md text-white me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal light m-0">
        <div class="toast-body text-white text-lg">
          يتم الآن الحذف ....
        </div>
      </div>

      <div class="toast fade hide p-2 bg-white" role="alert" aria-live="assertive" id="successToast" aria-atomic="true">
        <div class="toast-header border-0">
          <i class="material-icons text-success ms-2">check</i>
          <span class="ms-auto font-weight-bold text-lg">نجاح</span>
          <i class="fas fa-times text-md me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal dark m-0">
        <div class="toast-body text-lg">
         تمت العملية بنجاح
        </div>
      </div>

  </div>
  <!--     toast end     -->

  <script>

    $(document).ready(function() {
    $.get("{{ route('dashboard.users.all') }}").done(function(data){
    var table = $('#users_table').DataTable( {
          pagingType: 'full_numbers',
          retrieve: true,
          pageLength:5,
          processing: true,
          lengthMenu : [5, 10, 25 , 50],
          searching: true,
          responsive: true,
          "scrollX": true,
          deferRender: true,
          select: true,
          select: {
                style: 'multi'
            },
          "language": {
            "lengthMenu": "عرض _MENU_ سطر في الصفحة",
            "zeroRecords": "لم يتم ايجاد اي عنصر - عذراً",
            "info": "عرض الصفحة _PAGE_ من _PAGES_",
            "infoEmpty": "لا يوجد اي عنصر متطابق",
            "infoFiltered": "(تم البحث في _MAX_  سطر)",
            "loadingRecords": "يتم التحميل ...",
            "processing":     "تتم المعالجة ...",
            "search":         "بحث :",
            "paginate": {
              "first":      "البداية",
              "last":       "النهاية",
              "next":       "التالي",
              "previous":   "السابق"
          },
        },

        "data": data,
        "order": [],
        "columns": [
        { "data": 'name' },
        { "data": 'email' },
        {
              "data": "role",
              "render" : function (data ,type , row) {
                if (data) {
                  return 'ادمن';
                }else{
                  return 'مستخدم';
                }
            },
        },
        
        {
              "data": "id",
              "render" : function (data ,type , row) {
                  return `
                <button class="btn btn-info" id='edit_user'><i class = "fa fa-wrench"> </i></button>
                <button class="btn btn-danger" id='delete_user' ><i class = "fa fa-trash"> </i> </button> `;

        },
        },
        
        ],
        
    } );

    $('#selected_all_rows_button').on( 'click', function () {
    table.rows({ page: 'current' }).select();
    });
    $('#deselected_all_rows_button').on( 'click', function () {
        table.rows({ page: 'current' }).deselect();
    });

    $('#selected_rows_delete_button').on( 'click', function () {
        var ids = table.rows( { selected: true } ).data().map( row => {
            return row.id;}).toArray();
        if(ids.length == 0){
            return false;
        }
        // console.log(ids.length);
        var infoDeleteingToast = document.getElementById('infoToast');
        var infoToast = bootstrap.Toast.getInstance(infoDeleteingToast);
        var successDeleteingToast = document.getElementById('successToast');
        var successToast = bootstrap.Toast.getInstance(successDeleteingToast);

        var rows_selected = table.rows('.selected');

        Swal.fire({
        title: 'هل أنت متأكد ؟',
        text: `  سيتم حذف ${ids.length} عنصر ولا يمكنك التراجع `,
        icon: 'warning',
        showCancelButton: true,
        cancelButtonText : 'الغاء',
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'نعم ، احذفه !'
        }).then((result) => {
            if (result.isConfirmed) {
                infoToast.show();
                $.ajax({
                type: "DELETE",
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                url: "/dashboard/users/"+ids,
                contentType: false,
                processData: false,
                success:function(data){
                        console.log("success");
                        console.log(data);
                        // window.location.href = window.location.href;
                        rows_selected.remove().draw();
                        infoToast.hide();
                        successToast.show();
                },
                error:function(error){
                        console.log("error");
                        console.log(error);
                }
            });
            }
        })
        });

        $('#users_table tbody').on( 'click', '#delete_user', function () {
            var infoDeleteingToast = document.getElementById('infoToast');
            var infoToast = bootstrap.Toast.getInstance(infoDeleteingToast);
            var successDeleteingToast = document.getElementById('successToast');
            var successToast = bootstrap.Toast.getInstance(successDeleteingToast);

            var data = table.row( $(this).parents('tr') ).data();
            var row_clicked = table.row($(this).parents('tr'));

            // if the table in responsive mode and the tr has a child
            if(!data){
              var data = table.row( $(this).closest('tr :not(.child)') ).data();
              var row_clicked = table.row($(this).closest('tr :not(.child)'));
            }

            Swal.fire({
            title: 'هل أنت متأكد ؟',
            text: "لا يمكنك التراجع عن ذلك !",
            icon: 'warning',
            showCancelButton: true,
            cancelButtonText : 'الغاء',
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'نعم ، احذفه !'
            }).then((result) => {
            if (result.isConfirmed) {
                infoToast.show();
                $.ajax({
                    type: "DELETE",
                    headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                    url: "/dashboard/users/"+data['id'],
                    contentType: false,
                    processData: false,
                    success:function(data){
                            console.log("success");
                            console.log(data);
                            row_clicked.remove().draw();
                            infoToast.hide();
                            successToast.show();
                    },
                    error:function(error){
                            console.log("error");
                            console.log(error);
                    }
                });
            }
            })
        } );
        $('#users_table tbody').on( 'click', '#edit_user', function () {
            var data = table.row( $(this).parents('tr') ).data();

            // if the table in responsive mode and the tr has a child
            if(!data){
              var data = table.row( $(this).closest('tr :not(.child)') ).data();
            }

            window.location.href = 	"/dashboard/users/"+data['id']+"/edit";
        } );
    });
    });

</script>

@endsection