routes/web.php
<?php

use App\Http\Controllers\admin\{AnswersController,
    AuthController,
    ClassesController,
    GeneralController,
    QuestionController,
    ResultController,
    SectionsController,
    StudentController,
    TestController,
    UserController};
use App\Http\Controllers\front\FrontController;
use App\Http\Controllers\WordParserController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

// Auth admin
Route::get('/login-admin', function () { return view('admin.login');})->name('admin.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::post('/authenticate-admin', [AuthController::class, 'authenticate_admin'])->name('admin.authenticate');

// Auth student
Route::get('/login-student', function () { return view('admin.students.login');})->name('student.login');
Route::post('/authenticate-student', [\App\Http\Controllers\student\AuthController::class, 'authenticate_student'])->name('student.authenticate');


//Dashboard
Route::group([
    'prefix' => '/dashboard',
    'middleware' => ['admin'],
    'as' => 'dashboard.'
],
    function () {
    Route::get('/', [GeneralController::class, 'dashboard_index'])->name('index');
    //datatable
    Route::get('users/all', [UserController::class, 'all_users'])->name('users.all');
    Route::get('classes/all', [ClassesController::class, 'all_classes'])->name('classes.all');
    Route::get('sections/{id}/get_all', [SectionsController::class, 'all_sections'])->name('sections.all');
    Route::get('questions/all', [QuestionController::class, 'all_questions'])->name('questions.all');
    Route::get('students/all', [StudentController::class, 'all_students'])->name('students.all');
    Route::get('questions/{question}/answers', [AnswersController::class, 'addAnswers'])->name('questions.answers');

    Route::get('tests/all', [TestController::class, 'all_tests'])->name('tests.all');
    Route::get('questions/{id}/get_all', [QuestionController::class, 'all_questions_test'])->name('questions.test');
    Route::delete('tests/{test_id}/remove_question/{question_id}', [TestController::class, 'remove_question'])->name('tests.remove_question');
    Route::post('tests/{test_id}/add_random_questions', [QuestionController::class, 'add_random_questions'])->name('tests.add_random_questions');
    Route::post('tests/{id}/add_question', [TestController::class, 'add_question'])->name('tests.add_question');
    Route::get('student/submitted-exam-results', [ResultController::class, 'submittedExamResults'])->name('submitted_exam_results');
    Route::get('admin/view-class-results', [ResultController::class, 'viewClassResults'])->name('view_class_results');
    Route::get('results/class/all/{class_id}', [ResultController::class, 'getViewClassResults'])->name('view_class_results.all');
    Route::get('admin/view/previous-tests/{result}', [ResultController::class, 'previousTests'])->name('previous.tests.view');
    Route::post('/questions/upload', [WordParserController::class, 'upload'])->name('questions.upload');


        //resource
    Route::resources([
        'users' => UserController::class,
    ]);
    Route::resources([
        'classes' => ClassesController::class,
    ]);
    Route::resources([
        'sections' => SectionsController::class,
    ]);
    Route::resources([
        'questions' => QuestionController::class,
    ]);
    Route::resources([
        'students' =>StudentController::class,
    ]);
    Route::resources([
        'tests' => TestController::class,
    ]);
    Route::resources([
        'answers' =>AnswersController::class,
    ]);
});



Route::group([
    'prefix' => '/student',
    'middleware' => ['student'],
    'as' => 'student.'
           ],function (){

    Route::post('test/show/',  [FrontController::class, 'showTest'])->name('show.test')->middleware('checkTestCompletion');
    Route::get('available-tests', [FrontController::class, 'availableTests'])->name('available.tests');

    Route::post('tests/submit/{test_id}', [FrontController::class, 'submitTest'])->name('submit.test')->middleware('checkTestCompletion');
    Route::get('/results', [FrontController::class, 'showResults'])->name('test.result');

});

Route::get('student/all-results/{student_id}', [ResultController::class, 'allResults'])->name('student.all-results-students');

Route::get('student/all-results', [ResultController::class, 'index'])->name('student.all-results');

// View Test Results
Route::get('/student/test/result/view/{result}', [ResultController::class, 'viewTestResults'])->name('student.test.result.view');
Route::get('/student/show/testResult/view/{result}', [ResultController::class, 'viewTestResultsForAdmin'])->name('student.show.test.result.admin');

// Delete Test Results
Route::delete('/student/test/result/delete/{id}', [ResultController::class, 'deleteTestResults'])->name('student.test.result.delete');
//

app/Models/Answers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answers extends Model
{
    use HasFactory;
    protected $guarded = [] ;

    public function class()
    {
        return $this->belongsTo(Question::class, 'question_id');
    }
}

app/Http/Controllers/admin/AnswersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Answers;
use App\Models\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AnswersController extends Controller
{
  public function addAnswers ($id)
  {
      $data = Question::findOrFail($id);
      $answers = Answers::where('question_id', $id)->get();
      return view('admin.answers.index', compact('data','answers'));
  }

    public function store(Request $request)
    {

        $request->validate([
            'question_id' => 'required',
            'answer_text' => 'required|string',
            'is_correct' => 'nullable',
        ]);

        $answer = new Answers([
            'question_id' => $request->question_id,
            'answer_text' => $request->input('answer_text'),
            'is_correct' => $request->input('is_correct'),
        ]);
        $answer->save();

        DB::table('questions_answers')->insert([
            'answer_id' => $answer->id,
            'question_id' => $request->question_id,
        ]);


        return redirect()->route('dashboard.questions.answers', $request->question_id)->with('success', 'Answer added successfully.');
    }
}

resources/views/admin/answers/edit.blade.php
@extends('admin.master')
@section('page-title', 'تعديل الصف ')
@section('navbar-title', 'تعديل الصف ')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize pe-3">تعديل الصف  </h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">

            <div class="col-lg-12 col-md-12 px-2">
                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm"></span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <script>
                    $("#alert_message").on("close.bs.alert", function () {
                        // hide the alert >>> not remove it
                        $("#alert_message").hide();
                        return false;
                    });
                </script>
               
                    
                        <form role="form" id="edit_data_form" class="text-end" enctype="multipart/form-data">
                            
                            <div class="row">
                                <div class="col-12 text-center my-3">
                                    <h4>تعديل الصف  </h4>
                                </div>
                                <div class="col-12 col-md-12">
                                    <label class="form-label">اسم الصف</label>
                                    <div class="input-group input-group-outline my-2">
                                        
                                        <input id="title" name="title" type="text" class="form-control" value="{{$data->title}}">
                                    </div>
                                </div>
                                
                                
                            </div>
                            

                            

                            <div class="row">
                                
                                <div class="col-12  my-3">
                                    <button type="submit" class="btn bg-gradient-success w-100 mt-2 text-lg">
                                        <span id="button_submit_text"><i class="fa fa-plus"></i> تحديث</span>
                                        <div class="spinner" style="display: none;">
                                          <div class="double-bounce1"></div>
                                          <div class="double-bounce2"></div>
                                        </div>
                                    </button>
                                </div>
                            </div>
                        </form>
                    
                
            </div>
            
        </div>
      </div>
    </div>
  </div>

  <!--     toast start     -->
  <div class="position-fixed top-0 start-0 p-lg-3" style="z-index: 11">
    <div class="toast fade hide p-2 mt-2 bg-gradient-info" role="alert" aria-live="assertive" id="infoToast" aria-atomic="true">
        <div class="toast-header bg-transparent border-0">
          <i class="material-icons text-white ms-2">notifications</i>
          <span class="ms-auto text-white font-weight-bold text-lg">اشعار</span>
          <i class="fas fa-times text-md text-white me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal light m-0">
        <div class="toast-body text-white text-lg">
          يتم الآن الحذف ....
        </div>
      </div>

      <div class="toast fade hide p-2 bg-white" role="alert" aria-live="assertive" id="successToast" aria-atomic="true">
        <div class="toast-header border-0">
          <i class="material-icons text-success ms-2">check</i>
          <span class="ms-auto font-weight-bold text-lg">نجاح</span>
          <i class="fas fa-times text-md me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal dark m-0">
        <div class="toast-body text-lg">
         تمت العملية بنجاح
        </div>
      </div>

  </div>
  <!--     toast end     -->

  

{{-- edit data method --}}
<script>


    $('#edit_data_form').on('submit', function(e) {
       e.preventDefault();

       $("#button_submit_text").hide();
       $(".spinner").show();
       $("#alert_message").hide();

       var uploadData = new FormData(this);
        uploadData.append('_method','PUT');
       $.ajax({
           type: "POST",
           headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
           url: '{{route('dashboard.classes.update',$data)}}',
           data: uploadData,
           contentType: false,
           processData: false,
           statusCode: {
                422: function(error) {
                    // Only if your server returns a 422 status code can it come in this block. :-)
                    var errors = error.responseJSON.errors;
                    // console.log(errors);
                    var alert_message = document.getElementById("alert_message");
                    $("#alert_message").show();
                    var ul = document.getElementById("errors_list");
                    $('#errors_list').empty();
                    Object.entries(errors).forEach(function([key, value]){
                        var li = document.createElement("li");
                        li.appendChild(document.createTextNode(value));
                        ul.appendChild(li);
                    }
                    );
                },
                403: function() {
                    // Only if your server returns a 403 status code can it come in this block. :-)
                }
            },
           success:function(data){
                console.log("success");
                console.log(data);
                $("#button_submit_text").show();
                $(".spinner").hide();
                window.location = '{{route('dashboard.classes.index')}}';
           },
           error:function(error){
                console.log("error");
                console.log(error);
                $("#button_submit_text").show();
                $(".spinner").hide();
                // myToast.show();
           }
       });
   });
</script>

@endsection

resources/views/admin/answers/index.blade.php
\@extends('admin.master')
@section('page-title', 'إضافة إجابات')
@section('navbar-title', 'إضافة إجابات')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize pe-3">إضافة إجابات للسؤال</h6>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <h5 class="mb-4">السؤال:</h5>
                    <div class="mb-4">
                        <p><strong>العنوان:</strong> {{ $data->title }}</p>
                        <p><strong>الوصف:</strong> {{ $data->description }}</p>
                        <p><strong>القيمة:</strong> {{ $data->value }}</p>
                    </div>

                    <h5 class="mb-4">الإجابات:</h5>
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0 table-hover">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7 ">نص الإجابة</th>
                                <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">إجابة صحيحة</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($answers as $answer)
                                <tr>
                                    <td class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">   <span class="badge badge-success ">{{ $answer->answer_text }}</span></td>
                                    <td>
                                        @if($answer->is_correct)
                                            <span class="badge badge-success dark-version">نعم</span>
                                        @else
                                            <span class="badge badge-danger dark-version">لا</span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    <!-- Add Answer Form -->
                    <h5 class="mt-5 mb-4">إضافة إجابة جديدة:</h5>
                    <form action="{{ route('dashboard.answers.store') }}" method="POST">
                        @csrf
                        <input type="hidden" name="question_id" value="{{ $data->id }}">
                        <div class="mb-3">
                            <label for="answer_text" class="form-label">نص الإجابة:</label>
                            <textarea class="form-control" id="answer_text" name="answer_text" required></textarea>
                        </div>
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="is_correct" name="is_correct" value="1">
                            <label class="form-check-label" for="is_correct">إجابة صحيحة</label>
                        </div>
                        <button type="submit" class="btn btn-success">إضافة الإجابة</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/answers/show.blade.php
@extends('admin.master')
@section('page-title', 'عرض الصف')
@section('navbar-title', 'عرض الصف')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize pe-3">تفاصيل اللصف </h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">

            <div class="col-lg-12 col-md-12 px-2">
                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm"></span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <script>
                    $("#alert_message").on("close.bs.alert", function () {
                        // hide the alert >>> not remove it
                        $("#alert_message").hide();
                        return false;
                    });
                </script>


                        <form role="form" id="add_sections_form" class="text-end" enctype="multipart/form-data">

                            <div class="row">
                                <div class="col-12 text-center my-3">
                                    <h4>إضافة شعبة جديدة</h4>
                                </div>
                                <div class="col-12 col-md-12">
                                    <label class="form-label">اسم الشعبة</label>
                                    <div class="input-group input-group-outline my-2">

                                        <input id="title" name="title" type="text" class="form-control">
                                        <input type="hidden" id="class_id" name="class_id" value="{{ $data->id }}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-12  my-3">
                                    <button type="submit" class="btn bg-gradient-success w-100 mt-2 text-lg">
                                        <span id="button_submit_text"><i class="fa fa-plus"></i> إضافة</span>
                                        <div class="spinner" style="display: none;">
                                          <div class="double-bounce1"></div>
                                          <div class="double-bounce2"></div>
                                        </div>
                                    </button>
                                </div>
                            </div>
                        </form>


            </div>
            <hr />
            <h4 class="my-3 text-center">جدول الشعب التابعة لهذا الصف</h4>
            <div class="table-responsive p-0">
                <table class="table align-items-center mb-0 table-hover " id="sections_table" style="width:100%">
                <thead>
                    <tr>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7 ps-2"> اسم الشعبة  </th>
                    <th class="text-secondary text-s opacity-7">الاجراءات</th>
                    </tr>
                </thead>
                </table>
            </div>
        </div>
      </div>
    </div>
  </div>

  <!--     toast start     -->
  <div class="position-fixed top-0 start-0 p-lg-3" style="z-index: 11">
    <div class="toast fade hide p-2 mt-2 bg-gradient-info" role="alert" aria-live="assertive" id="infoToast" aria-atomic="true">
        <div class="toast-header bg-transparent border-0">
          <i class="material-icons text-white ms-2">notifications</i>
          <span class="ms-auto text-white font-weight-bold text-lg">اشعار</span>
          <i class="fas fa-times text-md text-white me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal light m-0">
        <div class="toast-body text-white text-lg">
          يتم الآن الحذف ....
        </div>
      </div>

      <div class="toast fade hide p-2 bg-white" role="alert" aria-live="assertive" id="successToast" aria-atomic="true">
        <div class="toast-header border-0">
          <i class="material-icons text-success ms-2">check</i>
          <span class="ms-auto font-weight-bold text-lg">نجاح</span>
          <i class="fas fa-times text-md me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal dark m-0">
        <div class="toast-body text-lg">
         تمت العملية بنجاح
        </div>
      </div>

  </div>
  <!--     toast end     -->



  <script>

    $(document).ready(function() {
    $.get("{{ url('dashboard/sections/'.$data->id.'/get_all') }}").done(function(data){
    var table = $('#sections_table').DataTable( {
          pagingType: 'full_numbers',
          retrieve: true,
          pageLength:10,
          processing: true,
          lengthMenu : [5, 10, 25 , 50],
          searching: true,
          responsive: true,
          deferRender: true,
          select: false,

          "language": {
            "lengthMenu": "عرض _MENU_ سطر في الصفحة",
            "zeroRecords": "لم يتم ايجاد اي عنصر - عذراً",
            "info": "عرض الصفحة _PAGE_ من _PAGES_",
            "infoEmpty": "لا يوجد اي عنصر متطابق",
            "infoFiltered": "(تم البحث في _MAX_  سطر)",
            "loadingRecords": "يتم التحميل ...",
            "processing":     "تتم المعالجة ...",
            "search":         "بحث :",
            "paginate": {
              "first":      "البداية",
              "last":       "النهاية",
              "next":       "التالي",
              "previous":   "السابق"
          },
        },

        "data": data,
        "order": [],
        "columns": [

        {
              "data": "title",
        },
        {
              "data": "id",
              "render" : function (data ,type , row) {
                  return `
                  <button class="btn btn-info" id='edit_sections'><i class = "fa fa-wrench"> </i></button> `;
        },
        },

        ],

    } );


        $('#sections_table tbody').on( 'click', '#edit_sections', function () {
            var data = table.row( $(this).parents('tr') ).data();

            // if the table in responsive mode and the tr has a child
            if(!data){
              var data = table.row( $(this).closest('tr :not(.child)') ).data();
            }

            window.location.href = 	"/dashboard/sections/"+data['id']+"/edit";
        } );
    });
    });

</script>

{{-- add new section method --}}
<script>

    $('#add_sections_form').on('submit', function(e) {
       e.preventDefault();
       $("#button_submit_text").hide();
       $(".spinner").show();
       $("#alert_message").hide();

       var uploadData = new FormData(this);

       $.ajax({
           type: "POST",
           headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
           url: '{{route('dashboard.sections.store')}}',
           data: uploadData,
           contentType: false,
           processData: false,
           statusCode: {
                422: function(error) {
                    // Only if your server returns a 422 status code can it come in this block. :-)
                    var errors = error.responseJSON.errors;
                    // console.log(errors);
                    var alert_message = document.getElementById("alert_message");
                    $("#alert_message").show();
                    var ul = document.getElementById("errors_list");
                    $('#errors_list').empty();
                    Object.entries(errors).forEach(function([key, value]){
                        var li = document.createElement("li");
                        li.appendChild(document.createTextNode(value));
                        ul.appendChild(li);
                    }
                    );
                },
                403: function() {
                    // Only if your server returns a 403 status code can it come in this block. :-)
                }
            },
           success:function(data){
                console.log("success");
                console.log(data);
                $("#button_submit_text").show();
                $(".spinner").hide();
                {{--window.location = '{{route('dashboard.classes.show')}}+';--}}
                    window.location = '{{ route('dashboard.classes.show', ['class' => $data->id]) }}';


           },
           error:function(error){
                console.log("error");
                console.log(error);
                $("#button_submit_text").show();
                $(".spinner").hide();
                // myToast.show();
           }
       });
   });
</script>

@endsection